#!/usr/bin/env bash
# Regenerate lua/organ/ast/html5_entities.lua from the canonical WHATWG HTML5
# named character reference list.  Only the semicolon-terminated forms are
# emitted; CommonMark requires the trailing ';'.  The value is the decoded
# character string (UTF-8).  This is a data table, not third-party code.
set -euo pipefail
URL="https://html.spec.whatwg.org/entities.json"
OUT="lua/organ/ast/html5_entities.lua"
TMP="$(mktemp)"
trap 'rm -f "$TMP"' EXIT
curl -fsSL "$URL" -o "$TMP"
python3 - "$TMP" "$OUT" <<'PY'
import sys, json
data = json.load(open(sys.argv[1]))
items = []
for name, ent in data.items():
    if not name.endswith(";"):
        continue
    key = name[1:-1]  # strip leading & and trailing ;
    chars = ent["characters"]
    # Lua long-bracket-safe: emit each byte as a \ddd decimal escape.
    esc = "".join("\\%d" % b for b in chars.encode("utf-8"))
    items.append((key, esc))
items.sort()
with open(sys.argv[2], "w") as f:
    f.write("-- HTML5 named character references (semicolon forms), name -> UTF-8\n")
    f.write("-- characters.  Generated by scripts/fetch-html5-entities.sh from the\n")
    f.write("-- canonical WHATWG entities.json; regenerate with that script.\n")
    f.write("return {\n")
    for key, esc in items:
        f.write('  ["%s"] = "%s",\n' % (key, esc))
    f.write("}\n")
print("wrote %d entities to %s" % (len(items), sys.argv[2]))
PY
