-- Regenerate lua/organ/ast/unicode_casefold.lua from a local copy of the
-- Unicode Character Database's CaseFolding.txt.  Portable pure Lua (no shell):
--   nvim -l scripts/gen-unicode-casefold.lua path/to/CaseFolding.txt
-- Emits the full case fold (the C "common" and F "full" mappings; the Turkic T
-- and simple S mappings are excluded) as a map from code point to the folded
-- UTF-8 string (\ddd byte escapes) -- CommonMark's link-label case fold.  This
-- is a data table, not third-party code.
local src = arg[1] or "CaseFolding.txt"
local out = arg[2] or "lua/organ/ast/unicode_casefold.lua"

local function utf8_encode(cp)
  if cp < 0x80 then
    return string.char(cp)
  elseif cp < 0x800 then
    return string.char(0xC0 + math.floor(cp / 0x40), 0x80 + cp % 0x40)
  elseif cp < 0x10000 then
    return string.char(
      0xE0 + math.floor(cp / 0x1000),
      0x80 + math.floor(cp / 0x40) % 0x40,
      0x80 + cp % 0x40
    )
  else
    return string.char(
      0xF0 + math.floor(cp / 0x40000),
      0x80 + math.floor(cp / 0x1000) % 0x40,
      0x80 + math.floor(cp / 0x40) % 0x40,
      0x80 + cp % 0x40
    )
  end
end

local folds = {}
for line in io.lines(src) do
  local body = line:gsub("#.*$", "")
  local code, status, mapping = body:match("^%s*(%x+)%s*;%s*(%a)%s*;%s*([%x ]+)%s*;")
  if code and (status == "C" or status == "F") then
    local s = {}
    for cp in mapping:gmatch("%x+") do
      s[#s + 1] = utf8_encode(tonumber(cp, 16))
    end
    folds[tonumber(code, 16)] = table.concat(s)
  end
end

local keys = {}
for k in pairs(folds) do
  keys[#keys + 1] = k
end
table.sort(keys)

local o = assert(io.open(out, "w"))
o:write("-- Generated by scripts/gen-unicode-casefold.lua; do not edit.\n")
o:write("-- Unicode full case fold (CaseFolding.txt C + F mappings): code point ->\n")
o:write("-- folded UTF-8 string.  CommonMark's link-label case fold.\n")
o:write("return {\n")
for _, k in ipairs(keys) do
  local esc = folds[k]:gsub(".", function(c)
    return string.format("\\%d", c:byte())
  end)
  o:write(string.format('  [%d] = "%s",\n', k, esc))
end
o:write("}\n")
o:close()
print(string.format("wrote %s: %d fold entries", out, #keys))
