-- Regenerate lua/organ/ast/html5_entities.lua from a local copy of the WHATWG
-- HTML5 named character reference list (entities.json).  Portable pure Lua:
--   nvim -l scripts/gen-html5-entities.lua path/to/entities.json
-- Only the semicolon-terminated forms are emitted (CommonMark requires the
-- trailing ';').  The value is the decoded character string as \ddd byte
-- escapes.  This is a data table, not third-party code.
local src = arg[1] or "entities.json"
local out = arg[2] or "lua/organ/ast/html5_entities.lua"

local fh = assert(io.open(src, "r"))
local data = vim.json.decode(fh:read("*a"))
fh:close()

local items = {}
for name, ent in pairs(data) do
  if name:sub(-1) == ";" then
    local key = name:sub(2, -2) -- strip leading '&' and trailing ';'
    local esc = {}
    for j = 1, #ent.characters do
      esc[#esc + 1] = string.format("\\%d", ent.characters:byte(j))
    end
    items[#items + 1] = { key, table.concat(esc) }
  end
end
table.sort(items, function(a, b)
  return a[1] < b[1]
end)

local o = assert(io.open(out, "w"))
o:write("-- HTML5 named character references (semicolon forms), name -> UTF-8\n")
o:write("-- characters.  Generated by scripts/gen-html5-entities.lua from the\n")
o:write("-- canonical WHATWG entities.json; regenerate with that script.\n")
o:write("return {\n")
for _, it in ipairs(items) do
  o:write(string.format('  ["%s"] = "%s",\n', it[1], it[2]))
end
o:write("}\n")
o:close()
print(string.format("wrote %d entities to %s", #items, out))
