-- Regenerate lua/organ/ast/unicode_punct.lua from a local copy of the Unicode
-- Character Database's UnicodeData.txt.  Portable pure Lua (no shell): download
-- UnicodeData.txt by any means, then run
--   nvim -l scripts/gen-unicode-punct.lua path/to/UnicodeData.txt
-- (or `lua scripts/gen-unicode-punct.lua ...`).  Emits sorted, merged [lo, hi]
-- code-point ranges for the Unicode general categories P* and S* -- CommonMark
-- 0.31.2's "Unicode punctuation".  This is a data table, not third-party code.
local src = arg[1] or "UnicodeData.txt"
local out = arg[2] or "lua/organ/ast/unicode_punct.lua"

local rows = {}
for line in io.lines(src) do
  local code, name, cat = line:match("^(%x+);([^;]*);([^;]*);")
  if code then
    rows[#rows + 1] = { tonumber(code, 16), name, cat }
  end
end

local function is_ps(cat)
  local c = cat:sub(1, 1)
  return c == "P" or c == "S"
end

local cps = {}
local i = 1
while i <= #rows do
  local cp, name, cat = rows[i][1], rows[i][2], rows[i][3]
  if name:match("First>$") and rows[i + 1] then
    if is_ps(cat) then
      cps[#cps + 1] = { cp, rows[i + 1][1] }
    end
    i = i + 2
  else
    if is_ps(cat) then
      cps[#cps + 1] = { cp, cp }
    end
    i = i + 1
  end
end

table.sort(cps, function(a, b)
  return a[1] < b[1]
end)

local merged = {}
for _, r in ipairs(cps) do
  local last = merged[#merged]
  if last and r[1] <= last[2] + 1 then
    last[2] = math.max(last[2], r[2])
  else
    merged[#merged + 1] = { r[1], r[2] }
  end
end

local fh = assert(io.open(out, "w"))
fh:write("-- Generated by scripts/gen-unicode-punct.lua; do not edit.\n")
fh:write("-- Sorted, non-overlapping [lo, hi] code-point ranges for the Unicode\n")
fh:write('-- general categories P* and S* (CommonMark\'s "Unicode punctuation").\n')
fh:write("-- A flat array: ranges[2k-1] = lo, ranges[2k] = hi.\n")
fh:write("return {\n")
local line = "  "
for _, r in ipairs(merged) do
  local chunk = string.format("%d, %d, ", r[1], r[2])
  if #line + #chunk > 78 then
    fh:write((line:gsub("%s+$", "")) .. "\n")
    line = "  "
  end
  line = line .. chunk
end
if line:match("%S") then
  fh:write((line:gsub("%s+$", "")) .. "\n")
end
fh:write("}\n")
fh:close()
print(string.format("wrote %s: %d ranges", out, #merged))
